# Generated by Django 2.1.7 on 2019-05-22 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ponto', '0002_auto_20190521_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='status_ponto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ponto.StatusPonto', verbose_name='Status ponto'),
        ),
    ]
