# Generated by Django 2.1.7 on 2019-05-31 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ponto', '0003_auto_20190521_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='ip_registro',
            field=models.CharField(blank=True, default='192.168.0.17', editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='conf_hora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ponto.ConfiguracaoHora', verbose_name='Configuração da hora'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ponto.Funcionario', verbose_name='Chefe Imediato'),
        ),
    ]
