# Generated by Django 2.1.7 on 2019-05-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ponto', '0004_auto_20190530_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargofuncionario',
            name='cargo_chefe',
            field=models.BooleanField(blank=True, null=True, verbose_name='Cargo Chefe'),
        ),
    ]
