# Generated by Django 2.1.7 on 2019-05-31 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ponto', '0005_cargofuncionario_cargo_chefe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargofuncionario',
            name='cargo_chefe',
            field=models.BooleanField(default=1, verbose_name='Cargo Chefe'),
            preserve_default=False,
        ),
    ]
